#!/usr/bin/env bun
// @hook-entry
/**
 * generate_map.native.ts — native TS port of _legacy_py/generate_map.py.
 * SessionStart: builds the multi-level navigable ecosystem map (index.md →
 * per-plugin index → recursive trees) and emits the SessionStart additionalContext.
 * Reuses the cartographer lib (inlined). Args mirror the Python; the script-
 * relative default uses PLUGIN_ROOT (bundle-safe, no import.meta.path).
 */
import { statSync, mkdirSync, readdirSync, writeFileSync, realpathSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { findMarketplacePlugins, readPluginMeta } from "./lib/detect-plugins.native";
import { mergeLines } from "./lib/merge-index.native";
import { scanPlugin } from "./lib/scan-plugins.native";
import { writePluginMap } from "./lib/write-plugin-map.native";

function isDir(p: string): boolean {
  try { return statSync(p).isDirectory(); } catch { return false; }
}

try {
  const arg1 = process.argv[2] ?? "";
  const arg2 = process.argv[3] ?? "";
  const pluginRoot = process.env.PLUGIN_ROOT ?? process.cwd();

  let pluginsDir = arg1 === "auto" ? findMarketplacePlugins()
    : arg1 ? arg1 : resolve(pluginRoot, "..");
  const outputDir = arg2 === "auto" ? join(dirname(resolve(pluginsDir)), ".cartographer")
    : arg2 ? arg2 : ".cartographer";

  // Python uses Path.resolve() which canonicalizes symlinks; match it so leaf
  // file-links (derived from this dir) are identical.
  try { pluginsDir = realpathSync(pluginsDir); } catch { pluginsDir = resolve(pluginsDir); }
  if (!isDir(pluginsDir)) process.exit(0);
  mkdirSync(outputDir, { recursive: true });

  const pluginDirs = readdirSync(pluginsDir)
    .filter((n) => !n.startsWith("_") && !n.startsWith(".") && isDir(join(pluginsDir, n)))
    .sort()
    .map((n) => join(pluginsDir, n));

  const now = new Date().toISOString().slice(0, 16).replace("T", " ");
  const indexLines = [
    `# Ecosystem Map (${pluginDirs.length} plugins)\n`,
    `> Auto-generated by cartographer — ${now}\n`,
  ];

  for (const pluginPath of pluginDirs) {
    const [version, pkgName] = readPluginMeta(pluginPath);
    const display = pkgName || pluginPath.slice(pluginPath.lastIndexOf("/") + 1);
    const items = scanPlugin(pluginPath);
    const agents = items.filter(([t]) => t === "agent").map(([, n]) => n);
    const agentsStr = agents.length ? agents.join(", ") : "(no agents)";
    const ver = version ? ` (v${version})` : "";
    indexLines.push(`- [${display}](./${display}/index.md)${ver} → ${agentsStr}`);
    writePluginMap(outputDir, display, version, items, pluginPath);
    writePluginMap(pluginPath, ".cartographer", version, items, pluginPath);
  }

  const indexPath = join(outputDir, "index.md");
  writeFileSync(indexPath, mergeLines(indexLines, indexPath).join("\n") + "\n", "utf-8");
  process.stderr.write(`cart plugins: ${pluginDirs.length} loaded\n`);

  const context =
    `Project map: .cartographer/project/index.md — navigate project files. ` +
    `Plugin skills map: ${outputDir}/index.md — navigate agent skills. ` +
    `Branches link to deeper index.md, leaves link to real files.`;
  console.log(JSON.stringify({
    hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: context },
  }));
} catch {
  /* match the Python: swallow any error silently */
}
