/**
 * exec-policy.ts — deposits Codex execpolicy Starlark rules generated by `@fusengine/harness`
 * into `<codexHome>/rules/fusengine.rules`, guarded by an idempotency marker.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import * as p from "@clack/prompts";
import { clearManagedDestination } from "./plugin-managed-destination";
import { generateExecPolicyRules, type GeneratedRules } from "./exec-policy-generator";

/** First-line marker identifying a `fusengine.rules` file as managed (drift-detectable via the version suffix). */
export const EXEC_POLICY_MARKER = "# fusengine:exec-policy";

function buildMarkerLine(harnessVersion: string): string {
	return `${EXEC_POLICY_MARKER} harness@${harnessVersion}`;
}

/**
 * Deposits generated execpolicy rules at `<codexHome>/rules/fusengine.rules`.
 *
 * Never fails the install: a missing/failing generator, or output without at least one
 * `prefix_rule(` block, only warns and leaves any existing file untouched — the Starlark is
 * validated in-memory BEFORE any write, so a bad generation run can never truncate or empty
 * a previously-deposited file. A foreign (unmarked) existing file at the destination is also
 * left untouched (delegated to {@link clearManagedDestination}, which warns).
 *
 * `generate` is injectable (defaults to the real harness invocation) so tests never shell out.
 */
export async function depositExecPolicy(
	codexHome: string,
	generate: (codexHome: string) => GeneratedRules | undefined = generateExecPolicyRules,
): Promise<void> {
	const rulesDir = join(codexHome, "rules");
	const destPath = join(rulesDir, "fusengine.rules");

	const generated = generate(codexHome);
	if (!generated || !generated.starlark.includes("prefix_rule(")) {
		p.log.warn("harness codex-rules produced no usable output — exec-policy rules not deposited");
		return;
	}

	await mkdir(rulesDir, { recursive: true });
	const cleared = await clearManagedDestination(destPath, "exec-policy", {}, EXEC_POLICY_MARKER);
	if (cleared === "skip") return;

	const content = `${buildMarkerLine(generated.harnessVersion)}\n${generated.starlark}`;
	await writeFile(destPath, content);
	p.log.success(`Deposited exec-policy rules → ${destPath} (harness@${generated.harnessVersion})`);
}
